<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * OntoWiki VoID module – VoID Helper template
 */
?>
<script type="text/javascript">
$(document).ready(function() {
    var createUrl  = urlBase + 'void/create';
    var suggestUrl = urlBase + 'void/suggest';

    function renderSuggestions(jsonData) {
        $('#results').empty();
        jQuery.each(jsonData, function() {
            var content = '';
            jQuery.each(this.properties, function() {
                content += '&rarr;&nbsp;<a title="'+ this.uri +'" href="'+ this.url +'">' + this.label + '</a> ';
            } );
            content = '<p class="'+ this.class +'">' + this.label + ':<br/> '+ content +'<p>';
            $('#results').append(content);

            //$("#" + this).text("My id is " + this + ".");
            //return (this != "four"); // will stop running to skip "five"
        });
    }

    $('#void-suggest').click(function () {
        //$(this).addClass('is-processing');
        $.getJSON(suggestUrl, function(jsonData) {renderSuggestions(jsonData); });
    });
});
</script>
<p class="messagebox info">Your knowledge base could be served as <a href="http://en.wikipedia.org/wiki/Linked_Data">Linked Data</a> and a valid <a href="http://www.w3.org/TR/void/">VoID description</a> fosters the consumption of your knowledge base.
</p>
<p>
<a id="void-create"  class="minibutton">Create / Update</a>
<a id="void-suggest" class="minibutton">Suggest</a>
</p>
<div id="results">
</div>
